// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmU6-EuiQfSAp1gMeXv_LRhYjhiBXEDKY',
    appId: '1:835761099193:web:1ec42df2dd7611b601a668',
    messagingSenderId: '835761099193',
    projectId: 'aura-11',
    authDomain: 'aura-11.firebaseapp.com',
    databaseURL: 'https://aura-11-default-rtdb.firebaseio.com',
    storageBucket: 'aura-11.appspot.com',
    measurementId: 'G-RQVZ0BSCZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVVl75QycwOecx4pZ9ZgUy1oHHFx0D9s',
    appId: '1:835761099193:android:a42c53efe106554901a668',
    messagingSenderId: '835761099193',
    projectId: 'aura-11',
    databaseURL: 'https://aura-11-default-rtdb.firebaseio.com',
    storageBucket: 'aura-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6Qy-6aKTMEDpFHW8DgXBLABB2oNKIc8',
    appId: '1:835761099193:ios:b43dd1b3875eb93901a668',
    messagingSenderId: '835761099193',
    projectId: 'aura-11',
    databaseURL: 'https://aura-11-default-rtdb.firebaseio.com',
    storageBucket: 'aura-11.appspot.com',
    iosClientId: '835761099193-jcovejtkc3dcpcgsk206r2vioidvicok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6Qy-6aKTMEDpFHW8DgXBLABB2oNKIc8',
    appId: '1:835761099193:ios:b43dd1b3875eb93901a668',
    messagingSenderId: '835761099193',
    projectId: 'aura-11',
    databaseURL: 'https://aura-11-default-rtdb.firebaseio.com',
    storageBucket: 'aura-11.appspot.com',
    iosClientId: '835761099193-jcovejtkc3dcpcgsk206r2vioidvicok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
